### ISSUE TITLE
v25.2.0 IOFreeze regressions

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#11282]
### Issue overview

I'm at a point where I'm starting to run the NREL/OpenStudio-resources regression tests with the v25.2.0-IOFreeze package.

This is going to be a running list of errors or regressions I'm finding.

### Operating System (Multiple choices)

Any

### Operating System Version

N/A

### Version of EnergyPlus

v25.2.0-IOFreeze

### Unmethours link or helpdesk ticket number

N/A

**Comment by jmarrec** [comment]
* [x] Filed at https://github.com/NREL/EnergyPlus/issues/11289

<details>

<summary>Case sensitivity error in getWaterTankStratifiedInput</summary>

```
ThermalStorage:ChilledWater:Stratified,
  Thermal Storage Chilled Water Stratified 1, !- Name
  50,                                     !- Tank Volume {m3}
  8,                                      !- Tank Height {m}
  VerticalCylinder,                       !- Tank Shape
  ,                                       !- Tank Perimeter {m}
  Schedule Ruleset 5,                     !- Setpoint Temperature Schedule Name
  2.5,                                    !- Deadband Temperature Difference {deltaC}
  ,                                       !- Temperature Sensor Height {m}
  ,                                       !- Minimum Temperature Limit {C}
  Autosize,                               !- Nominal Cooling Capacity {W}
  Outdoors,                               !- Ambient Temperature Indicator
  Schedule Ruleset 6,                     !- Ambient Temperature Schedule Name
  ,                                       !- Ambient Temperature Zone Name
  Thermal Storage Chilled Water Stratified 1 OA Node, !- Ambient Temperature Outdoor Air Node Name
  ,                                       !- Uniform Skin Loss Coefficient per Unit Area to Ambient Temperature {W/m2-K}
  Node 140,                               !- Use Side Inlet Node Name
  Node 141,                               !- Use Side Outlet Node Name
  1,                                      !- Use Side Heat Transfer Effectiveness
  ,                                       !- Use Side Availability Schedule Name
  Autocalculate,                          !- Use Side Inlet Height {m}
  0,                                      !- Use Side Outlet Height {m}
  Autosize,                               !- Use Side Design Flow Rate {m3/s}
  Node 51,                                !- Source Side Inlet Node Name
  Node 142,                               !- Source Side Outlet Node Name
  1,                                      !- Source Side Heat Transfer Effectiveness
  ,                                       !- Source Side Availability Schedule Name
  0,                                      !- Source Side Inlet Height {m}
  Autocalculate,                          !- Source Side Outlet Height {m}
  Autosize,                               !- Source Side Design Flow Rate {m3/s}
  4,                                      !- Tank Recovery Time {hr}
  Fixed,                                  !- Inlet Mode
  6,                                      !- Number of Nodes
  0,                                      !- Additional Destratification Conductivity {W/m-K}
  0,                                      !- Node 1 Additional Loss Coefficient {W/K}
  0,                                      !- Node 2 Additional Loss Coefficient {W/K}
  0,                                      !- Node 3 Additional Loss Coefficient {W/K}
  0,                                      !- Node 4 Additional Loss Coefficient {W/K}
  0,                                      !- Node 5 Additional Loss Coefficient {W/K}
  0,                                      !- Node 6 Additional Loss Coefficient {W/K}
  0,                                      !- Node 7 Additional Loss Coefficient {W/K}
  0,                                      !- Node 8 Additional Loss Coefficient {W/K}
  0,                                      !- Node 9 Additional Loss Coefficient {W/K}
  0;                                      !- Node 10 Additional Loss Coefficient {W/K}
```

**Notice the casing "Autocalculate"**

`libc++abi: terminating due to uncaught exception of type nlohmann::json_abi_v3_12_0::detail::type_error: [json.exception.type_error.302] type must be number, but is string`

```
(lldb) f 15
frame #15: 0x000000010798cba8 libenergyplusapi.25.2.0.dylib`EnergyPlus::WaterThermalTanks::getWaterTankStratifiedInput(state=0x000000016fdfbda8, objectType="ThermalStorage:ChilledWater:Stratified") at WaterThermalTanks.cc:3978:58
   3975          if (SourceOutletHeight == "AutoCalculate") {
   3976              Tank.SourceOutletHeight = Tank.Height;
   3977          } else {
-> 3978              Tank.SourceOutletHeight = SourceOutletHeight.get<Real64>();
   3979          }
   3980          if (Tank.SourceOutletHeight > Tank.Height) {
   3981              ShowSevereError(state,

(lldb) p SourceOutletHeight
(const nlohmann::basic_json<>::value_type) {
  m_data = {
    m_type = string
    m_value = {
      object = 0x0000000756076420 size=0
      array = 0x0000000756076420 size=error: Start of vector data begins after end pointer.
      string = "Autocalculate"
      binary = 0x0000000756076420
      boolean = true
      number_integer = 31508096032
      number_unsigned = 31508096032
      number_float = 1.5567067815278098E-313
    }
  }
}
```


Root cause:

* https://github.com/NREL/EnergyPlus/pull/11033
* Specifically https://github.com/NREL/EnergyPlus/commit/2fdc9c6464f#diff-ff2acea307277f17be8bc6dad46c58d457095812df4ed13f4ccfd9a09aa6f1caR3867

It's an easy fix. @yujiex FYI

---

Here this is field isn't even autocalculatable, so there should not be an if:

https://github.com/NREL/EnergyPlus/blob/0befe779fe9721745ba31a65f877cc05905ac6b3/src/EnergyPlus/WaterThermalTanks.cc#L3936-L3941

The field has a default, so getRealFieldValue should be used instead

----

Here you can see it correctly calls getRealFieldValue already on line 3972, so the block below is 1) pointless and 2) wrong.

https://github.com/NREL/EnergyPlus/blob/0befe779fe9721745ba31a65f877cc05905ac6b3/src/EnergyPlus/WaterThermalTanks.cc#L3972-L3979

</details>

**Comment by jmarrec** [comment]
After fixing this, I'm getting a new crash that I didn't have before

```diff
    ** Warning ** ThermalStorage:ChilledWater:Stratified = Thermal Storage Chilled Water Stratified 1:  More Additional Loss Coefficients were entered than the number of nodes; extra coefficients will not be used
+   ** Warning ** Water heater named THERMAL STORAGE CHILLED WATER STRATIFIED 1has heater capacity set to AUTOSIZE but it is missing associated WaterHeater:Sizing object
+   **  Fatal  ** GetWaterThermalTankInput: Errors found in processing Water Thermal Tank input.
```

The second Warning is new, should at least be a Severe if it's going to fatal, and  is missing a space.

**Comment by jmarrec** [comment]
Here is a MCVE-ish that exhibits the regression: works with 25.1.0, does't with 25.2.0 IOFreeze

[thermal_storage_chw_rb_2510.idf.txt](https://github.com/user-attachments/files/23054601/thermal_storage_chw_rb_2510.idf.txt)

**Comment by jmarrec** [comment]
We have some EUI deviations for the OpenStudio-resources?

<img width="386" height="216" alt="Image" src="https://github.com/user-attachments/assets/2ee3e56a-12e1-48fc-a7b7-f9e5b417e140" />

end use by fuel type:

<img width="1310" height="1069" alt="Image" src="https://github.com/user-attachments/assets/7dcce463-9f72-4a3d-b230-55447e924155" />

**Comment by jmarrec** [comment]
I was super confused as to why my file with the ThermalStorage:ChilledWater:Stratified was running in E+ 25.1.0 and no longer does, when the file had a blank "Maximum Cooling Capacity".

It's because that was understood as 0.0 by the getObject, https://github.com/NREL/EnergyPlus/pull/11033#discussion_r2460578145

**Comment by shorowit** [comment]
Here are a couple regressions I noticed for the following model w/ EnergyPlus 25.2.0-6a6bc0728b:
- [x] There is a new warning that `Object=Coil:WaterHeating:AirToWaterHeatPump:Wrapped=water heater coil` is unused; it is definitely used. https://github.com/NREL/EnergyPlus/issues/11304
- [x] A `epluspsz.csv` output file is now created, but all it has is a `Time` column and nothing else. Previously this file was not created. Addressed by https://github.com/NREL/EnergyPlus/issues/11274#issuecomment-3408246700 and https://github.com/NREL/EnergyPlus/pull/11292.

[ep25_1.zip](https://github.com/user-attachments/files/23126397/ep25_1.zip)
[ep25_2.zip](https://github.com/user-attachments/files/23126406/ep25_2.zip)

**Comment by jmarrec** [comment]
Can you use a `WaterHeater:Sizing` with a `ThermalStorage:ChilledWater:Stratified`  (Or HotWater, Or the Mixed version) object actually?

None of the example files have it.

This warning + the code makes me think yes.

but the IDD indicates otherwise:

```
WaterHeater:Sizing,
       \min-fields 4
       \memo This input object is used with WaterHeater:Mixed or
       \memo with WaterHeater:Stratified to autosize tank volume and heater capacity
       \memo This object is not needed if water heaters are not autosized.
  A1 , \field WaterHeater Name
       \required-field
       \type object-list
       \object-list WaterHeaterNames
```

Only `WaterHeater:Mixed `and `WaterHeater:Stratified` have that reference `WaterHeaterNames` and the memo is pretty explicit too

**Comment by rraustad** [comment]
@jmarrec it looks like to me that WaterHeater:Sizing inputs are specific to a HW tank. But since the WaterHeaterSizingData class is  member of WaterThermalTankData then yes the sizing object could be used for any of the thermal tanks. But the sizing inputs are mostly related to a HW heater, not thermal storage. The "recovery time" is a WH Standard metric and, while I'm not positive, I think these sizing inputs are helpful in calculating that value and maybe some other WH specific metrics.

**Comment by jmarrec** [comment]
To reiterate in case you missed it: this currently Fatals if the `ThermalStorage:ChilledWater:Stratified` has autosized fields but no WaterHeater:Sizing...

```diff
+   ** Warning ** Water heater named THERMAL STORAGE CHILLED WATER STRATIFIED 1has heater capacity set to AUTOSIZE but it is missing associated WaterHeater:Sizing object
+   **  Fatal  ** GetWaterThermalTankInput: Errors found in processing Water Thermal Tank input.
```

I'm going to go on the assumption that a WaterHeater:Sizing (with PeakDraw) for eg is appropriate...

**Comment by jmarrec** [comment]
Since this issue has more on it that the WaterThermalTank now, I filed a separate issue that I will address:

* https://github.com/NREL/EnergyPlus/issues/11289

**Comment by shorowit** [comment]
> A `epluspsz.csv` output file is now created, but all it has is a `Time` column and nothing else. Previously this file was not created (presumably because it's empty).

@rraustad I see now that this is a new E+ 25.2 file added in https://github.com/NREL/EnergyPlus/pull/11147. Can you have E+ not write the file when it's empty? Also, it should really be added to `OutputControl:Files` so that a user can turn it off if they don't want it.

**Comment by rraustad** [comment]
@shorowit I will look into adding to OutputControl:Files. @mjwitte had the same empty file comment and I thought I already fixed the empty file. I'll try to track down where that stands.

**Comment by shorowit** [comment]
Thanks @rraustad! I haven't tested the newest IO freeze release from yesterday, so it's possible it's fixed in there.

**Comment by rraustad** [comment]
Well, [this comment](https://github.com/NREL/EnergyPlus/issues/11274#issuecomment-3408246700) says I fixed it. But I did not do the OutputControl:Files update.

**Comment by shorowit** [comment]
@jmarrec Can this issue be closed?
