### ISSUE TITLE
Dataset GLHERefData.idf has two flow rates which are incorrect

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4417]
Helpdesk Ticket 9340

Same question asked on the yahoo group.
 Linda Lawrie on 13 April 2014 02:04 PM
 
However, he did not point out the error on the dataset on the yahoo group.
 Linda Lawrie on 14 April 2014 01:29 PM

Thank you for finding that error.

 As far as the plant loop supply/demand side temperatures, the program iterates on a solution. That solution may not converge completely which would mean additional iterations are required to reach a solution.

 This object controls the number of iterations a plant loop will make before converging.

 ConvergenceLimits,
 1, !- Minimum System Timestep {minutes}
 20; !- Maximum HVAC Iterations

 As shown below, the last 2 fields in this object were left blank and the defaults are a minimum of 2 and maximum of 8 plant iterations.
 you could change, or add, this object to be (or other choices as dictated by the simulation results):

 ConvergenceLimits,
 1, !- Minimum System Timestep {minutes}
 20, !- Maximum HVAC Iterations
 8, !- Minimum Plant Iterations
 10; !- Maximum Plant Iterations

 ConvergenceLimits,
 \memo Specifies limits on HVAC system simulation timesteps and iterations.
 \memo This item is an advanced feature that should be used only with caution.
 \unique-object
 N1 , \field Minimum System Timestep
 \units minutes
 \type integer
 \note 0 sets the minimum to the zone timestep (ref: Timestep)
 \note 1 is normal (ratchet down to 1 minute)
 \note setting greater than zone timestep (in minutes) will effectively set to zone timestep
 \minimum 0
 \maximum 60
 N2 , \field Maximum HVAC Iterations
 \type integer
 \default 20
 \minimum 1
 N3 , \field Minimum Plant Iterations
 \note Controls the minimum number of plant system solver iterations within a single HVAC iteration
 \note Larger values will increase runtime but might improve solution accuracy for complicated plant systems
 \note Complex plants include: several interconnected loops, heat recovery, thermal load following generators, etc.
 \type integer
 \default 2
 \minimum 1
 N4 ; \field Maximum Plant Iterations
 \note Controls the maximum number of plant system solver iterations within a single HVAC iteration
 \note Smaller values might decrease runtime but could decrease solution accuracy for complicated plant systems
 \type integer
 \default 8
 \minimum 2

 'Richard Raustad

leif
User
Posted on: 13 April 2014 03:12 AM

The data in GLHERefData.idf of "0.00303, !- Design Flow Rate {m3/s}" for "!************ LINE CONFIGURATION: 1 x 2, line, Standard Grout *****************" and for 
 "!********* LINE CONFIGURATION: 1 x 2, line, thermally enhanced Grout **********" should be 
 " "0.000303, !- Design Flow Rate {m3/s} ". There is a decimal point error.
 One more puzzle: the result of PlantHorizontalGroundHX.idf of ExampleFiles , the two 
 temperature of inlet and outlet of the Plant Loop Supply Side is not equal to the two 
 temperature of inlet and outlet of the Plant Loop Demand Side. So the heat flux of plant 
 loop is not conserved. Is this a debug?

**Comment by mjwitte** [comment]
@mmatts Would you be able to confirm whether this is a real issue or not?

**Comment by mmatts** [comment]
@mjwitte Sure, I'll take a look.

**Comment by Myoldmopar** [comment]
That's a good point here, with the GLHE inputs changing @mmatts I'm sure this needs to be updated.

**Comment by mmatts** [comment]
@myoldmopar @mjwitte

The decimal point error referenced was already fixed.

I applied input changes to GLHERefData.idf. I can push those shortly.

It’s still unclear to me whether the mismatch between supply-demand side temperatures is a bug.
I took the PlantHorizontalGroundHX.idf and have been running some cases hoping to coax out the error.
In summary, what we have is this: supply side has a pump and a horizontal GHX in that order from inlet to outlet; the pump is 100% efficient at 100 W; the demand side has a load profile extracting 500 W from the system. I moved the HGX *deep* into the ground so there should be no ground surface effects and ran an annual simulation hoping to drive everything to steady-state so the we wouldn't have to worry about the tank (which is set to zero, ```0.0,    !- Plant Loop Volume```).

[Here](https://www.dropbox.com/s/htvfsejua2px9ov/HT_Rates.png?dl=0) is a plot of the supply/demand side HT rates, Pump Fluid Heat Gain, GHX HT Rate, and the pump + the GHX (which should equal the supply side.) Sorry for the links, I tried to embed images in but they weren't coming up. Maybe I can't use Dropbox to host them? I tired following [this example.](https://github.com/NREL/EnergyPlus/issues/4588)

Demand side eventually comes up to around 500 W extracted, which is where the load profile setpoint is, however, the supply side only comes to around 400 W added. The sum of the pump heat + the GHX looks good. I'm estimating supply/demand side HT rate by mdot*cp*DT across the supply/demand side inlet/outlet node temps. Cp is coming from some VBA antifreeze prop functions that have been used at OSU for ages.

[Here](https://www.dropbox.com/s/7gbg9itph1vo1qh/DT.png?dl=0) Is a plot of the supply inlet minus demand outlet temps and supply outlet minus demand inlet temps. If I'm correct when I step through the code, it looks like the tank is between the supply outlet - demand inlet which would probably explain the small temperature difference between the loop sides (diffs on the order of E-6 at SS.) For the other side, however, we see SS diffs of around 0.01 C, which seems a little high if there is nothing going on in between.

Now, if you take that supply inlet - demand outlet temp diff (which means that supply inlet is 0.01 C higher than the demand outlet) and apply it to the supply side HT rate and plot again, we get [this](https://www.dropbox.com/s/bi58160fqvvea44/HT_Rates_Compensated.png?dl=0) plot, which is starting to look about right. 

To me it looks like something is off, by maybe I've missed something. Could either of you give some direction on this.

**Comment by MatthewSteen** [comment]
@mmatts you can drag/drop images into the text box or upload using a dialog box.

![energyplus_issue](https://cloud.githubusercontent.com/assets/8397034/6697657/b3afc68e-ccb7-11e4-9fdf-5d356ab21595.png)

**Comment by mmatts** [comment]
@MatthewSteen thanks for pointing that out; I definitely missed that. I was trying to do it manually from Dropbox but GitHub made it even simpler.

**Comment by Myoldmopar** [comment]
@mmatts Is there still an issue here?  If not, please reference the fix and close this.

**Comment by mitchute** [comment]
@Myoldmopar @mjwitte I had a look at this again. The flow rate error in GLHERefData was corrected prior to changing the GHLE inputs [here](https://github.com/NREL/EnergyPlus/commit/8c48f443b56941d5725892b9e4c046559a72da2d)

As for the supply side delta T not matching the demand side, I'm not seeing any issues. This is for PlantHorizontalGroundHX.idf running an annual simulation with a constant load.

![figure_1](https://cloud.githubusercontent.com/assets/2985979/9771267/98e44bcc-56fa-11e5-84d2-72a25a813828.png)

![figure_2](https://cloud.githubusercontent.com/assets/2985979/9771250/7a3702c8-56fa-11e5-961e-91843411ef6b.png)

HT Rates are calculated separately from E+ with the flow rate and temperature difference. There is a small difference between sides, but it doesn't appear significant. I recommend closing the issue. Let me know if you want me to look into it further.

**Comment by mjwitte** [comment]
Closed per comment from @mmatts on Sep 9, 2015.
