### ISSUE TITLE
LEED Summary Report General Improvements

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/EnergyPlus#4588]
**EAp2-3. Energy Type Summary Report**
Looks like the district energy (cooling and heating) virtual rate calc might be wrong in this report. For example if I calculate what LEED calls the virtual (blended) rate for electricity, district cooling, and district heating using the total cost from eplustbl Tariff Reports and the total energy from eplustbl Building Energy Performance, the virtual electricity rate will match but the district cooling and heating will not. In fact, I'm not sure where the virtual rate for district energy is coming from - it doesn't match what I calc for either cooling, heating, or a blend of the two. Also, it would be more helpful to have the district cooling and district heating in separate rows. 

The image below comes from an OpenStudio 1.5.0 model using a custom Xcel EDA Tariff Selection and Model Setup measure with district cooling ($7.1/MMBtu) and heating ($12.299/MMBtu) energy charges but no damand charges. The virtual electricity rate is slightly higher than the energy charge due to demand charges. I confirmed that the measure is in fact changes the out.idf with the correct rates mentioned above.

![image](https://cloud.githubusercontent.com/assets/8397034/5036542/fff3222e-6b3d-11e4-92c0-6749c7387a39.png)

Moved to #5614

**Comment by MatthewSteen** [comment]
@mjwitte - I would also like to submit an issue for the LEED EAp2-4/5 Table, would you prefer that I combine here for general LEED output improvements or submit a new issue?

LEED Table EAp2-4/5 should be changed to report the absolute peak demand by end use instead of the peak demand relative to the building peak. This is what USGBC/GBCI reviewers look for to calculate full load equivalent hours by end use.

**Comment by mjwitte** [comment]
@MatthewSteen It's OK to add the second issue here.  We need defect file(s) that show the problems.  Do you have write permission to EnergyPlusDevSupport?  If so, put the idf files in EnergyPlusDevSupport\DefectFiles\4000s\4588  If not, just e-mail them to me and I will put them up.

**Comment by MatthewSteen** [comment]
**Table EAp2-4/5**
Should be changed to report the absolute peak demand by end use instead of the peak demand relative to the building peak. This is what USGBC/GBCI reviewers look for to calculate full load equivalent hours by end use.

Moved to #5559

**Comment by MatthewSteen** [comment]
@JasonGlazer I don't have write permission to EnergyPlusDevSupport, but can send IDFs to your Gard.com address if needed.

**Comment by JasonGlazer** [comment]
Please email me them. IDFs that demonstrate an issue are always appreciated.

**Comment by MatthewSteen** [comment]
**Tables EAp2-4/5, EAp2-17a, EAp2-17b**
Service Water Heating doesn't show up as an end use in these tables unless a `WaterHeater` object is providing SHW. If another type of equipment such as a `BoilerHotWater` or `HeatExchangerFluidToFluid` is providing SHW to the WaterUseConnection and WaterUseEquipment the energy use will be zero.

Moved to #5613

**Comment by MatthewSteen** [comment]
**EAp2-2. Advisory Messages**
Total unmet hours not summing correctly and don't match `Time Setpoint Not Met` table from `System Summary` report:

Number of hours heating loads not met | 30.00
Number of hours cooling loads not met    | 10.00
Number of hours not met | 55.00

Fixed in #5296

**Comment by JasonGlazer** [comment]
@MatthewSteen This issue has become too many different pieces. Would it be possible for you to make sure all of these issues are still valid and post them to separate issues with either a way to reproduce the problem or each a file that demonstrates the problem?

**Comment by MatthewSteen** [comment]
@JasonGlazer will do.

**Comment by JasonGlazer** [comment]
@MatthewSteen I am going to work on the district heating virtual rate problem. I think the other issue that you mentioned in this issue have been split out. If I missed any please make a new issue for them.

**Comment by JasonGlazer** [comment]
@MatthewSteen so can this issue be closed now?
